// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:y
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7p8dTR1gBOV3w1CHVn824OxfZrqPuV48',
    appId: '1:1028891368919:web:611753df36456beca47f92',
    messagingSenderId: '1028891368919',
    projectId: 'management-panel-418df',
    authDomain: 'management-panel-418df.firebaseapp.com',
    storageBucket: 'management-panel-418df.appspot.com',
    measurementId: 'G-ZW6P5SKSPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDA8zSvRJy8xOqVRdLcQdzJx007AQ3LU',
    appId: '1:1028891368919:android:768f5f82c9e20cf3a47f92',
    messagingSenderId: '1028891368919',
    projectId: 'management-panel-418df',
    storageBucket: 'management-panel-418df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQglOZ9U5EDYiaHYmMty-n0WftoBjvjpE',
    appId: '1:1028891368919:ios:bc5135345f345fa3a47f92',
    messagingSenderId: '1028891368919',
    projectId: 'management-panel-418df',
    storageBucket: 'management-panel-418df.appspot.com',
    iosClientId:
        '1028891368919-dq25grsak1b2roqt6b9frku1ldahs7ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.telecallingTrippens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQglOZ9U5EDYiaHYmMty-n0WftoBjvjpE',
    appId: '1:1028891368919:ios:c6a93e25db84d332a47f92',
    messagingSenderId: '1028891368919',
    projectId: 'management-panel-418df',
    storageBucket: 'management-panel-418df.appspot.com',
    iosClientId:
        '1028891368919-ub7u8plr5smotebiamoi17uu5etufpaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.telecallingTrippens.RunnerTests',
  );
}
