/// Flutter icons TelecallingIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TelecallingIcons
///      fonts:
///       - asset: fonts/TelecallingIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class TelecallingIcons {
  TelecallingIcons._();

  static const String _kFontFam = 'TelecallingIcons';

  static const IconData calendar = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData time_square = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData window_close = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calendar_check =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData call_2 = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData category_1 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData chart_areaspline_variant =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData chart_box = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cog = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData group = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData lock_1 = IconData(0xe811, fontFamily: _kFontFam);
}
